import Head from "next/head";
import Banner from "../src/components/commons/layout/banner/banner";
import MainPage from "../src/components/units/main/main.container";
import Header from "../src/components/commons/layout/header/header.container";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Banner />
      <MainPage />
    </>
  );
}
